# Team.destroy_all
# Team.create(name: "Philadelphia Eagles")
# Team.create(name: "New York Giants")
# abc = Team.create(name: "New York Jets")


Player.destroy_all
#New York Jets
Player.create(name: "Jamal Adams", player_number: "33", player_position: "DB", player_status: "ACT", birth_date: "10/17/1995",height:"6'1",weight:"213",college: "LSU")
Player.create(name: "Robby Anderson",player_number: "11",player_position: "WR", player_status: "ACT", birth_date: "5/9/1993",height:"6'3",weight:"190",college: "Temple")
Player.create(name: "Henry Anderson",player_number: "96",player_position: "DE", player_status: "ACT", birth_date: "8/3/1991",height:"6'6",weight:"301",college: "Stanford")
Player.create(name: "Jeremiah Attaochu",player_number: "55",player_position: "LB", player_status: "ACT", birth_date: "1/17/1993",height:"6'3",weight:"252",college: "Georgia Tech")
Player.create(name: "Kelvin Beachum",player_number: "68",player_position: "OT", player_status: "ACT", birth_date: "6/8/1989",height:"6'3",weight:"308",college: "Southern Methodist")
Player.create(name: "Braden, Ben",player_number: "69",player_position: "OG", player_status: "ACT", birth_date: "3/9/1994",height:"6'6",weight:"329",college: "Michigan")
Player.create(name: "Terrence Brooks",player_number: "23",player_position: "DB", player_status: "ACT", birth_date: "3/2/1992",height:"5'11",weight:"200",college: "Florida State")
Player.create(name: "Juston Burris",player_number: "32",player_position: "CB", player_status: "ACT", birth_date: "8/4/1993",height:"6'0",weight:"212",college: "North Carolina State")
Player.create(name: "Trenton Cannon",player_number: "40",player_position: "RB", player_status: "ACT", birth_date: "7/23/1994",height:"5'11",weight:"185",college: "Virginia State")
Player.create(name: "James Carpenter",player_number: "77",player_position: "OG", player_status: "ACT", birth_date: "3/22/1989",height:"6'5",weight:"321",college: "Alabama")
Player.create(name: "Morris Claiborne",player_number: "21",player_position: "RB", player_status: "ACT", birth_date: "2/7/1990",height:"5'11",weight:"192",college: "LSU")
Player.create(name: "Brandon Copeland",player_number: "51",player_position: "OG", player_status: "ACT", birth_date: "7/2/1991",height:"6'3",weight:"263",college: "Pennsylvania")
Player.create(name: "Isaiah Crowell",player_number: "20",player_position: "WR", player_status: "ACT", birth_date: "1/8/1993",height:"5'11",weight:"225",college: "Alabama State")
Player.create(name: "Sam Darnold",player_number: "14",player_position: "P", player_status: "ACT", birth_date: "6/5/1997",height:"6'3",weight:"225",college: "USC")
Player.create(name: "Dozier, Dakota",player_number: "70",player_position: "DT", player_status: "ACT", birth_date: "4/30/1991",height:"6'4",weight:"313",college: "Furman")
Player.create(name: "Lac Edwards",player_number: "4",player_position: "RB", player_status: "ACT", birth_date: "4/27/1992",height:"6'4",weight:"209",college: "Sam Houston State")
Player.create(name: "Quincy Enunwa",player_number: "81",player_position: "C", player_status: "ACT", birth_date: "5/31/1992",height:"6'2",weight:"225",college: "Nebraska")
Player.create(name: "Foley Fatukasi",player_number: "94",player_position: "LB", player_status: "ACT", birth_date: "3/4/1995",height:"6'4",weight:"318",college: "Connecticut")
Player.create(name: "Jonotthan Harrison",player_number: "78",player_position: "RB", player_status: "ACT", birth_date: "8/25/1991",height:"6'4",weight:"300",college: "Florida")
Player.create(name: "Thomas Hennessy",player_number: "42",player_position: "RB", player_status: "ACT", birth_date: "6/11/1994",height:"6'2",weight:"246",college: "Duke")
Player.create(name: "Chris Herndon",player_number: "89",player_position: "LB", player_status: "ACT", birth_date: "2/23/1996",height:"6'4",weight:"253",college: "Miami (Fla.)")
Player.create(name: "Neville Hewitt",player_number: "46",player_position: "WR", player_status: "ACT", birth_date: "4/6/1993",height:"6'2",weight:"234",college: "Marshall")
Player.create(name: "Ben Ijalana",player_number: "71",player_position: "TE", player_status: "RES", birth_date: "8/6/1989",height:"6'4",weight:"322",college: "Villanova")
Player.create(name: "Jordan Jenkins",player_number: "48",player_position: "DB", player_status: "ACT", birth_date: "7/1/1994",height:"6'3",weight:"259",college: "Georgia")
Player.create(name: "Trumaine Johnson",player_number: "22",player_position: "WR", player_status: "ACT", birth_date: "1/1/1990",height:"6'2",weight:"213",college: "Montana")
Player.create(name: "Derrick Jones",player_number: "31",player_position: "K", player_status: "ACT", birth_date: "12/4/1994",height:"6'2",weight:"188",college: "Mississippi")
Player.create(name: "Jermaine Kearse",player_number: "10",player_position: "OT", player_status: "ACT", birth_date: "2/6/1990",height:"6'1",weight:"209",college: "Washington")
Player.create(name: "Darron Lee",player_number: "58",player_position: "CB", player_status: "ACT", birth_date: "10/18/1994",height:"6'1",weight:"232",college: "Ohio State")
Player.create(name: "Jordan Leggett",player_number: "86",player_position: "WR", player_status: "ACT", birth_date: "1/31/1995",height:"6'5",weight:"258",college: "Clemson")
Player.create(name: "Spencer Long",player_number: "61",player_position: "RB", player_status: "ACT", birth_date: "11/8/1990",height:"6'5",weight:"318",college: "Nebraska")
Player.create(name: "Frankie Luvu",player_number: "50",player_position: "DT", player_status: "ACT", birth_date: "9/19/1996",height:"6'3",weight:"236",college: "Washington State")
Player.create(name: "Josh Martin",player_number: "95",player_position: "DT", player_status: "ACT", birth_date: "11/7/1991",height:"6'3",weight:"245",college: "Columbia")
Player.create(name: "Maye, Marcus",player_number: "26",player_position: "TE", player_status: "ACT", birth_date: "3/9/1993",height:"6'0",weight:"207",college: "Florida")
Player.create(name: "Josh McCown",player_number: "15",player_position: "OG", player_status: "ACT", birth_date: "7/4/1979",height:"6'4",weight:"218",college: "Sam Houston State")
Player.create(name: "Elijah McGuire",player_number: "25",player_position: "DT", player_status: "RES", birth_date: "6/1/1994",height:"'10",weight:"214",college: "Louisiana-Lafayette")
Player.create(name: "Steve McLendon",player_number: "99",player_position: "CB", player_status: "ACT", birth_date: "1/3/1986",height:"6'3",weight:"310",college: "Troy")
Player.create(name: "Doug Middleton",player_number: "36",player_position: "OT", player_status: "ACT", birth_date: "9/25/1993",height:"6'0",weight:"210",college: "Appalachian State")
Player.create(name: "Miles, Rontez",player_number: "45",player_position: "RB", player_status: "PUP", birth_date: "11/25/1988",height:"6'0",weight:"203",college: "California (PA)")
Player.create(name: "Jason Myers",player_number: "2",player_position: "RB", player_status: "ACT", birth_date: "5/12/1991",height:"5'10",weight:"190",college: "Marist")
Player.create(name: "Parry Nickerson",player_number: "43",player_position: "K", player_status: "ACT", birth_date: "10/11/1994",height:"5'10",weight:"182",college: "Tulane")
Player.create(name: "Charone Peake",player_number: "17",player_position: "TE", player_status: "ACT", birth_date: "10/16/1992",height:"6'2",weight:"209",college: "Clemson")
Player.create(name: "Mike Pennel",player_number: "98",player_position: "DT", player_status: "ACT", birth_date: "5/9/1991",height:"6'4",weight:"332",college: "Colorado State-Pueblo")
Player.create(name: "Kevin Pierre-Louis",player_number: "56",player_position: "OT", player_status: "SUS", birth_date: "10/7/1991",height:"6'0",weight:"230",college: "Boston College")
Player.create(name: "Bilal Powell",player_number: "29",player_position: "OG", player_status: "ACT", birth_date: "10/27/1988",height:"5'10",weight:"204",college: "Louisville")
Player.create(name: "Pryor, Terrelle",player_number: "1",player_position: "DT", player_status: "ACT", birth_date: "6/20/1989",height:"6'4",weight:"228",college: "Ohio State")
Player.create(name: "Brent Qvale",player_number: "79",player_position: "LB", player_status: "ACT", birth_date: "3/11/1991",height:"6'7",weight:"315",college: "Nebraska")
Player.create(name: "Andre Roberts",player_number: "3",player_position: "WR", player_status: "ACT", birth_date: "1/9/1988",height:"5'11",weight:"195",college: "The Citadel")
Player.create(name: "Darryl Roberts",player_number: "27",player_position: "RB", player_status: "ACT", birth_date: "11/26/1990",height:"6'0",weight:"182",college: "Marshall")
Player.create(name: "Rashard Robinson",player_number: "30",player_position: "WR", player_status: "SUS", birth_date: "7/23/1995",height:"6'2",weight:"177",college: "LSU")
Player.create(name: "Brandon Shell",player_number: "72",player_position: "RB", player_status: "ACT", birth_date: "2/6/1992",height:"6'5",weight:"324",college: "South Carolina")
Player.create(name: "Nathan Shepherd",player_number: "97",player_position: "OT", player_status: "ACT", birth_date: "10/9/1993",height:"6'4",weight:"315",college: "Fort Hays State")
Player.create(name: "Buster Skrine",player_number: "41",player_position: "CB", player_status: "ACT", birth_date: "4/26/1989",height:"5'9",weight:"185",college: "Tennessee-Chattanooga")
Player.create(name: "Neal Sterling",player_number: "85",player_position: "OT", player_status: "ACT", birth_date: "1/14/1992",height:"6'4",weight:"257",college: "Monmouth (N.J.)")
Player.create(name: "ArDarius Stewart",player_number: "18",player_position: "LB", player_status: "SUS", birth_date: "12/8/1993",height:"6'0",weight:"205",college: "Alabama")
Player.create(name: "Eric Tomlinson",player_number: "83",player_position: "LB", player_status: "ACT", birth_date: "4/22/1992",height:"6'6",weight:"263",college: "Texas-El Paso")
Player.create(name: "J.J. Wilcox",player_number: "27",player_position: "DB", player_status: "ACT", birth_date: "2/14/1991",height:"6'0",weight:"212",college: "Georgia Southern")
Player.create(name: "Leonard Williams",player_number: "92",player_position: "WR", player_status: "ACT", birth_date: "6/20/1994",height:"6'5",weight:"302",college: "USC")
Player.create(name: "Avery Williamson",player_number: "54",player_position: "DT", player_status: "ACT", birth_date: "3/9/1992",height:"6'1",weight:"246",college: "Kentucky")
Player.create(name: "Brian Winters",player_number: "67",player_position: "DT", player_status: "ACT", birth_date: "7/10/1991",height:"6'4",weight:"320",college: "Kent State")


# Philadelphia Eagles
Player.create(name: "Nelson Agholor",player_number: "13",player_position: "LB", player_status: "ACT", birth_date: "5/24/1993",height:"6'0",weight:"198",college: "USC")
Player.create(name: "Jay Ajayi",player_number: "26",player_position: "WR", player_status: "ACT", birth_date: "6/15/1993",height:"6'0",weight:"223",college: "Boise State")
Player.create(name: "D.J. Alexander",player_number: "57",player_position: "TE", player_status: "ACT", birth_date: "9/30/1991",height:"6'2",weight:"233",college: "Oregon State")
Player.create(name: "Derek Barnett",player_number: "96",player_position: "RB", player_status: "ACT", birth_date: "6/25/1996",height:"6'3",weight:"259",college: "Tennessee")
Player.create(name: "Michael Bennett",player_number: "77",player_position: "DT", player_status: "ACT", birth_date: "11/13/1985",height:"6'4",weight:"274",college: "Texas A&M")
Player.create(name: "Elie Bouka",player_number: "38",player_position: "OG", player_status: "RES", birth_date: "8/15/1992",height:"6'1",weight:"205",college: "Calgary")
Player.create(name: "Nigel Bradham",player_number: "53",player_position: "TE", player_status: "ACT", birth_date: "9/4/1989",height:"6'2",weight:"241",college: "Florida State")
Player.create(name: "Brandon Brooks",player_number: "79",player_position: "LB", player_status: "ACT", birth_date: "8/19/1989",height:"6'5",weight:"335",college: "Miami (Ohio)")
Player.create(name: "DeAndre Carter",player_number: "16",player_position: "OG", player_status: "ACT", birth_date: "4/10/1993",height:"5'8",weight:"190",college: "Sacramento State")
Player.create(name: "Corey Clement",player_number: "30",player_position: "WR", player_status: "ACT", birth_date: "11/2/1994",height:"5'10",weight:"220",college: "Wisconsin")
Player.create(name: "Fletcher Cox",player_number: "91",player_position: "OT", player_status: "ACT", birth_date: "12/13/1990",height:"6'4",weight:"310",college: "Mississippi State")
Player.create(name: "Ronald Darby",player_number: "21",player_position: "DT", player_status: "ACT", birth_date: "1/2/1994",height:"5'11",weight:"193",college: "Florida State")
Player.create(name: "Rasul Douglas",player_number: "32",player_position: "LB", player_status: "ACT", birth_date: "8/29/1994",height:"6'2",weight:"209",college: "West Virginia")
Player.create(name: "Jake Elliott",player_number: "4",player_position: "RB", player_status: "ACT", birth_date: "1/21/1995",height:"5'9",weight:"167",college: "Memphis")
Player.create(name: "Zach Ertz",player_number: "86",player_position: "TE", player_status: "ACT", birth_date: "11/10/1990",height:"6'5",weight:"250",college: "Stanford")
Player.create(name: "Nick Foles",player_number: "9",player_position: "RB", player_status: "ACT", birth_date: "1/20/1989",height:"6'6",weight:"243",college: "Arizona")
Player.create(name: "Nate Gerry",player_number: "47",player_position: "RB", player_status: "ACT", birth_date: "2/23/1995",height:"6'2",weight:"230",college: "Nebraska")
Player.create(name: "Shelton Gibson",player_number: "18",player_position: "WR", player_status: "ACT", birth_date: "3/20/1994",height:"5'11",weight:"191",college: "West Virginia")
Player.create(name: "Dallas Goedert",player_number: "88",player_position: "DT", player_status: "ACT", birth_date: "1/3/1995",height:"6'5",weight:"256",college: "South Dakota State")
Player.create(name: "Brandon Graham",player_number: "55",player_position: "LB", player_status: "ACT", birth_date: "4/3/1988",height:"6'2",weight:"265",college: "Michigan")
Player.create(name: "Corey Graham",player_number: "24",player_position: "OG", player_status: "ACT", birth_date: "7/25/1985",height:"6'0",weight:"196",college: "New Hampshire")
Player.create(name: "Kamu Grugier-Hill",player_number: "54",player_position: "TE", player_status: "ACT", birth_date: "5/16/1994",height:"6'2",weight:"230",college: "Eastern Illinois")
Player.create(name: "Hall, Deiondre'",player_number: "32",player_position: "K", player_status: "ACT", birth_date: "5/31/1994",height:"6'2",weight:"206",college: "Northern Iowa")
Player.create(name: "Bruce Hector",player_number: "98",player_position: "LB", player_status: "ACT", birth_date: "10/7/1994",height:"6'2",weight:"296",college: "South Florida")
Player.create(name: "Jordan Hicks",player_number: "58",player_position: "LB", player_status: "ACT", birth_date: "6/27/1992",height:"6'1",weight:"236",college: "Texas")
Player.create(name: "Mack Hollins",player_number: "10",player_position: "RB", player_status: "RES", birth_date: "9/16/1993",height:"6'4",weight:"221",college: "North Carolina")
Player.create(name: "Alshon Jeffery",player_number: "17",player_position: "DT", player_status: "ACT", birth_date: "2/14/1990",height:"6'3",weight:"218",college: "South Carolina")
Player.create(name: "Malcolm Jenkins",player_number: "27",player_position: "CB", player_status: "ACT", birth_date: "12/20/1987",height:"6'0",weight:"204",college: "Ohio State")
Player.create(name: "Lane Johnson",player_number: "65",player_position: "DB", player_status: "ACT", birth_date: "5/8/1990",height:"6'6",weight:"317",college: "Oklahoma")
Player.create(name: "Cameron Johnston",player_number: "1",player_position: "OG", player_status: "ACT", birth_date: "2/24/1992",height:"5'11",weight:"194",college: "Ohio State")
Player.create(name: "Sidney Jones",player_number: "22",player_position: "TE", player_status: "ACT", birth_date: "5/21/1996",height:"6'0",weight:"181",college: "Washington")
Player.create(name: "Jason Kelce, ",player_number: "62",player_position: "RB", player_status: "ACT", birth_date: "11/5/1987",height:"6'3",weight:"295",college: "Cincinnati")
Player.create(name: "Chris Long",player_number: "56",player_position: "LB", player_status: "ACT", birth_date: "3/28/1985",height:"6'3",weight:"270",college: "Virginia")
Player.create(name: "Rick Lovato",player_number: "45",player_position: "K", player_status: "ACT", birth_date: "9/9/1992",height:"6'2",weight:"249",college: "Old Dominion")
Player.create(name: "Avonte Maddox",player_number: "29",player_position: "RB", player_status: "ACT", birth_date: "3/31/1996",height:"5'9",weight:"184",college: "Pittsburgh")
Player.create(name: "Jordan Mailata",player_number: "68",player_position: "DT", player_status: "ACT", birth_date: "3/31/1997",height:"6'8",weight:"346",college: "Unknown")
Player.create(name: "Chris Maragos",player_number: "42",player_position: "OG", player_status: "PUP", birth_date: "1/6/1987",height:"5'10",weight:"200",college: "Wisconsin")
Player.create(name: "Rodney McLeod",player_number: "23",player_position: "C", player_status: "ACT", birth_date: "6/23/1990",height:"5'10",weight:"195",college: "Virginia")
Player.create(name: "Jalen Mills",player_number: "31",player_position: "K", player_status: "ACT", birth_date: "4/6/1994",height:"6'0",weight:"191",college: "LSU")
Player.create(name: "Haloti Ngata",player_number: "94",player_position: "WR", player_status: "ACT", birth_date: "1/21/1984",height:"6'4",weight:"340",college: "Oregon")
Player.create(name: "Josh Perkins",player_number: "83",player_position: "RB", player_status: "ACT", birth_date: "8/5/1993",height:"6'3",weight:"223",college: "Washington")
Player.create(name: "Jason Peters",player_number: "71",player_position: "OT", player_status: "ACT", birth_date: "1/22/1982",height:"6'4",weight:"328",college: "Arkansas")
Player.create(name: "Matt Pryor",player_number: "69",player_position: "WR", player_status: "ACT", birth_date: "12/16/1994",height:"6'7",weight:"332",college: "Texas Christian")
Player.create(name: "LaRoy Reynolds",player_number: "50",player_position: "K", player_status: "ACT", birth_date: "11/3/1990",height:"6'1",weight:"240",college: "Virginia")
Player.create(name: "Richard Rodgers",player_number: "82",player_position: "RB", player_status: "RES", birth_date: "1/22/1992",height:"6'4",weight:"257",college: "California")
Player.create(name: "Isaac Seumalo",player_number: "73",player_position: "QB", player_status: "ACT", birth_date: "10/29/1993",height:"6'4",weight:"303",college: "Oregon State")
Player.create(name: "Gannon Sinclair, ",player_number: "48",player_position: "C", player_status: "RES", birth_date: "2/5/1993",height:"6'7",weight:"258",college: "Missouri State")
Player.create(name: "Wendell Smallwood",player_number: "28",player_position: "K", player_status: "ACT", birth_date: "1/20/1994",height:"5'10",weight:"208",college: "West Virginia")
Player.create(name: "Darren Sproles",player_number: "43",player_position: "WR", player_status: "ACT", birth_date: "6/20/1983",height:"5'6",weight:"190",college: "Kansas State")
Player.create(name: "Nate Sudfeld",player_number: "7",player_position: "LB", player_status: "ACT", birth_date: "10/7/1993",height:"6'6",weight:"227",college: "Indiana")
Player.create(name: "Josh Sweat",player_number: "75",player_position: "RB", player_status: "ACT", birth_date: "3/29/1997",height:"6'5",weight:"251",college: "Florida State")
Player.create(name: "Destiny Vaeao",player_number: "97",player_position: "DB", player_status: "ACT", birth_date: "1/15/1994",height:"6'4",weight:"299",college: "Washington State")
Player.create(name: "Halapoulivaati Vaitai",player_number: "72",player_position: "TE", player_status: "ACT", birth_date: "6/16/1993",height:"6'6",weight:"320",college: "Texas Christian")
Player.create(name: "Mike Wallace",player_number: "14",player_position: "WR", player_status: "ACT", birth_date: "8/1/1986",height:"6'0",weight:"200",college: "Mississippi")
Player.create(name: "Chance Warmack",player_number: "67",player_position: "LB", player_status: "ACT", birth_date: "9/14/1991",height:"6'2",weight:"323",college: "Alabama")
Player.create(name: "Toby Weathersby",player_number: "74",player_position: "RB", player_status: "RES", birth_date: "9/19/1996",height:"6'6",weight:"308",college: "LSU")
Player.create(name: "Carson Wentz",player_number: "11",player_position: "WR", player_status: "ACT", birth_date: "12/30/1992",height:"6'5",weight:"237",college: "North Dakota State")
Player.create(name: "Markus Wheaton",player_number: "80",player_position: "OG", player_status: "ACT", birth_date: "2/7/1991",height:"5'11",weight:"185",college: "Oregon State")
Player.create(name: "Stefen Wisniewski",player_number: "61",player_position: "DT", player_status: "ACT", birth_date: "3/22/1989",height:"6'3",weight:"305",college: "Penn State")
Player.create(name: "Paul Worrilow",player_number: "50",player_position: "RB", player_status: "RES", birth_date: "5/1/1990",height:"6'0",weight:"230",college: "Delaware")



#New York Giants

Player.create(name: "Apple Eli",player_number: "24",player_position: "RB", player_status: "ACT", birth_date: "5/24/1993",height:"6'0",weight:"198",college: "USC")
Player.create(name: "Armbriter Thruston",player_number: "57",player_position: "WR", player_status: "ACT", birth_date: "6/15/1993",height:"6'0",weight:"223",college: "Boise State")
Player.create(name: "Armstrong Ray-ray",player_number: "55",player_position: "LB", player_status: "ACT", birth_date: "9/30/1991",height:"6'2",weight:"233",college: "Oregon State")
Player.create(name: "Barkley Saquon",player_number: "26",player_position: "QB", player_status: "ACT", birth_date: "6/25/1996",height:"6'3",weight:"259",college: "Tennessee")
Player.create(name: "Barrin Conner",player_number: "53",player_position: "K", player_status: "ACT", birth_date: "11/13/1985",height:"6'4",weight:"274",college: "Texas A&M")
Player.create(name: "Beal Sam",player_number: "38",player_position: "DT", player_status: "RES", birth_date: "8/15/1992",height:"6'1",weight:"205",college: "Calgary")
Player.create(name: "Beckham Odell",player_number: "13",player_position: "RB", player_status: "ACT", birth_date: "9/4/1989",height:"6'2",weight:"241",college: "Florida State")
Player.create(name: "Brown Eva",player_number: "67",player_position: "LB", player_status: "ACT", birth_date: "8/19/1989",height:"6'5",weight:"335",college: "Miami (Ohio)")
Player.create(name: "Carter Lorenzo",player_number: "59",player_position: "WR", player_status: "ACT", birth_date: "4/10/1993",height:"5'8",weight:"190",college: "Sacramento State")
Player.create(name: "Chandler Sean",player_number: "36",player_position: "CB", player_status: "ACT", birth_date: "11/2/1994",height:"5'10",weight:"220",college: "Wisconsin")
Player.create(name: "Clay kaelin",player_number: "15",player_position: "WR", player_status: "ACT", birth_date: "12/13/1990",height:"6'4",weight:"310",college: "Mississippi State")
Player.create(name: "Collins Landon",player_number: "21",player_position: "OG", player_status: "ACT", birth_date: "1/2/1994",height:"5'11",weight:"193",college: "Florida State")
Player.create(name: "Davis Tee",player_number: "58",player_position: "K", player_status: "ACT", birth_date: "8/29/1994",height:"6'2",weight:"209",college: "West Virginia")
Player.create(name: "DeOssie Dontte",player_number: "51",player_position: "DT", player_status: "ACT", birth_date: "1/21/1995",height:"5'9",weight:"167",college: "Memphis")
Player.create(name: "Edwards Mario",player_number: "99",player_position: "CB", player_status: "ACT", birth_date: "11/10/1990",height:"6'5",weight:"250",college: "Stanford")
Player.create(name: "Ellison Rhett",player_number: "85",player_position: "LB", player_status: "ACT", birth_date: "1/20/1989",height:"6'6",weight:"243",college: "Arizona")
Player.create(name: "Engram Evan",player_number: "88",player_position: "RB", player_status: "ACT", birth_date: "2/23/1995",height:"6'2",weight:"230",college: "Nebraska")
Player.create(name: "Flowers Ereack",player_number: "74",player_position: "LB", player_status: "ACT", birth_date: "3/20/1994",height:"5'11",weight:"191",college: "West Virginia")
Player.create(name: "Gallman Wayne",player_number: "22",player_position: "RB", player_status: "ACT", birth_date: "1/3/1995",height:"6'5",weight:"256",college: "South Dakota State")
Player.create(name: "Gates Nick",player_number: "65",player_position: "OG", player_status: "ACT", birth_date: "4/3/1988",height:"6'2",weight:"265",college: "Michigan")
Player.create(name: "Goodson Bj",player_number: "93",player_position: "C", player_status: "ACT", birth_date: "7/25/1985",height:"6'0",weight:"196",college: "New Hampshire")
Player.create(name: "Greco Jhon",player_number: "73",player_position: "K", player_status: "ACT", birth_date: "5/16/1994",height:"6'2",weight:"230",college: "Eastern Illinois")
Player.create(name: "Halapio Jon",player_number: "75",player_position: "RB", player_status: "ACT", birth_date: "5/31/1994",height:"6'2",weight:"206",college: "Northern Iowa")
Player.create(name: "Hamiltom Antonio",player_number: "30",player_position: "DT", player_status: "ACT", birth_date: "10/7/1994",height:"6'2",weight:"296",college: "South Florida")
Player.create(name: "Harrison Damon",player_number: "98",player_position: "LB", player_status: "ACT", birth_date: "6/27/1992",height:"6'1",weight:"236",college: "Texas")
Player.create(name: "Hernandez Will",player_number: "71",player_position: "RB", player_status: "RES", birth_date: "9/16/1993",height:"6'4",weight:"221",college: "North Carolina")
Player.create(name: "Hill B J",player_number: "95",player_position: "DT", player_status: "ACT", birth_date: "2/14/1990",height:"6'3",weight:"218",college: "South Carolina")
Player.create(name: "Jenkins Janoris",player_number: "20",player_position: "CB", player_status: "ACT", birth_date: "12/20/1987",height:"6'0",weight:"204",college: "Ohio State")
Player.create(name: "Jordan Mike",player_number: "33",player_position: "DB", player_status: "ACT", birth_date: "5/8/1990",height:"6'6",weight:"317",college: "Oklahoma")
Player.create(name: "latimere cody",player_number: "12",player_position: "TE", player_status: "ACT", birth_date: "2/24/1992",height:"5'11",weight:"194",college: "Ohio State")
Player.create(name: "laulett Kyle",player_number: "17",player_position: "TB", player_status: "ACT", birth_date: "5/21/1996",height:"6'0",weight:"181",college: "Washington")
Player.create(name: "Manning Eli ",player_number: "10",player_position: "OG", player_status: "ACT", birth_date: "11/5/1987",height:"6'3",weight:"295",college: "Cincinnati")
Player.create(name: "Martin Kareem",player_number: "96",player_position: "QB", player_status: "ACT", birth_date: "3/28/1985",height:"6'3",weight:"270",college: "Virginia")
Player.create(name: "Josh Maouro",player_number: "97",player_position: "K", player_status: "ACT", birth_date: "9/9/1992",height:"6'2",weight:"249",college: "Old Dominion")
Player.create(name: "Moor Kam",player_number: "29",player_position: "OG", player_status: "ACT", birth_date: "3/31/1996",height:"5'9",weight:"184",college: "Pittsburgh")
Player.create(name: "Patric Omeaha",player_number: "45",player_position: "LB", player_status: "ACT", birth_date: "3/31/1997",height:"6'8",weight:"346",college: "Unknown")
Player.create(name: "rielly curtis",player_number: "35",player_position: "DT", player_status: "PUP", birth_date: "1/6/1987",height:"5'10",weight:"200",college: "Wisconsin")
Player.create(name: "Shepard Russell",player_number: "81",player_position: "WR", player_status: "ACT", birth_date: "6/23/1990",height:"5'10",weight:"195",college: "Virginia")
Player.create(name: "Rosas Aldrick",player_number: "2",player_position: "TE", player_status: "ACT", birth_date: "4/6/1994",height:"6'0",weight:"191",college: "LSU")
Player.create(name: "Smith Shane",player_number: "87",player_position: "OG", player_status: "ACT", birth_date: "1/21/1984",height:"6'4",weight:"340",college: "Oregon")
Player.create(name: "Shane Sith ",player_number: "31",player_position: "RB", player_status: "ACT", birth_date: "8/5/1993",height:"6'3",weight:"223",college: "Washington")
Player.create(name: "Solder Nate",player_number: "43",player_position: "WR", player_status: "ACT", birth_date: "1/22/1982",height:"6'4",weight:"328",college: "Arkansas")
Player.create(name: "Stupar Nate",player_number: "3",player_position: "RB", player_status: "ACT", birth_date: "12/16/1994",height:"6'7",weight:"332",college: "Texas Christian")
Player.create(name: "Rosas Aldrick",player_number: "54",player_position: "C", player_status: "ACT", birth_date: "11/3/1990",height:"6'1",weight:"240",college: "Virginia")
Player.create(name: "Skolick Kristsjan",player_number: "23",player_position: "LB", player_status: "RES", birth_date: "1/22/1992",height:"6'4",weight:"257",college: "California")
Player.create(name: "Alex Tanney",player_number: "3",player_position: "LB", player_status: "ACT", birth_date: "10/29/1993",height:"6'4",weight:"303",college: "Oregon State")
Player.create(name: "Thomas Michel",player_number: "77",player_position: "RB", player_status: "RES", birth_date: "2/5/1993",height:"6'7",weight:"258",college: "Missouri State")
Player.create(name: "Vernon Oliver",player_number: "70",player_position: "RB", player_status: "ACT", birth_date: "1/20/1994",height:"5'10",weight:"208",college: "West Virginia")
Player.create(name: "Webb Bw",player_number: "82",player_position: "RB", player_status: "ACT", birth_date: "6/20/1983",height:"5'6",weight:"190",college: "Kansas State")
Player.create(name: "William Jordan",player_number: "54",player_position: "CB", player_status: "ACT", birth_date: "10/7/1993",height:"6'6",weight:"227",college: "Indiana")
Player.create(name: "Wheeler Card",player_number: "52",player_position: "QB", player_status: "ACT", birth_date: "3/29/1997",height:"6'5",weight:"251",college: "Florida State")
Player.create(name: "Kerry Wilams",player_number: "94",player_position: "DT", player_status: "ACT", birth_date: "1/15/1994",height:"6'4",weight:"299",college: "Washington State")
Player.create(name: "Tanny Alex",player_number: "23",player_position: "RB", player_status: "ACT", birth_date: "6/16/1993",height:"6'6",weight:"320",college: "Texas Christian")
Player.create(name: "Mike Wallace",player_number: "72",player_position: "LBS", player_status: "ACT", birth_date: "8/1/1986",height:"6'0",weight:"200",college: "Mississippi")



#New York Giants

Player.create(name: "Apple Eli",player_number: "24",player_position: "RB", player_status: "ACT", birth_date: "5/24/1993",height:"6'0",weight:"198",college: "USC")
Player.create(name: "Armbriter Thruston",player_number: "57",player_position: "WR", player_status: "ACT", birth_date: "6/15/1993",height:"6'0",weight:"223",college: "Boise State")
Player.create(name: "Armstrong Ray-ray",player_number: "55",player_position: "LB", player_status: "ACT", birth_date: "9/30/1991",height:"6'2",weight:"233",college: "Oregon State")
Player.create(name: "Barkley Saquon",player_number: "26",player_position: "QB", player_status: "ACT", birth_date: "6/25/1996",height:"6'3",weight:"259",college: "Tennessee")
Player.create(name: "Barrin Conner",player_number: "53",player_position: "K", player_status: "ACT", birth_date: "11/13/1985",height:"6'4",weight:"274",college: "Texas A&M")
Player.create(name: "Beal Sam",player_number: "38",player_position: "DT", player_status: "RES", birth_date: "8/15/1992",height:"6'1",weight:"205",college: "Calgary")
Player.create(name: "Beckham Odell",player_number: "13",player_position: "RB", player_status: "ACT", birth_date: "9/4/1989",height:"6'2",weight:"241",college: "Florida State")
Player.create(name: "Brown Eva",player_number: "67",player_position: "LB", player_status: "ACT", birth_date: "8/19/1989",height:"6'5",weight:"335",college: "Miami (Ohio)")
Player.create(name: "Carter Lorenzo",player_number: "59",player_position: "WR", player_status: "ACT", birth_date: "4/10/1993",height:"5'8",weight:"190",college: "Sacramento State")
Player.create(name: "Chandler Sean",player_number: "36",player_position: "CB", player_status: "ACT", birth_date: "11/2/1994",height:"5'10",weight:"220",college: "Wisconsin")
Player.create(name: "Clay kaelin",player_number: "15",player_position: "WR", player_status: "ACT", birth_date: "12/13/1990",height:"6'4",weight:"310",college: "Mississippi State")
Player.create(name: "Collins Landon",player_number: "21",player_position: "OG", player_status: "ACT", birth_date: "1/2/1994",height:"5'11",weight:"193",college: "Florida State")
Player.create(name: "Davis Tee",player_number: "58",player_position: "K", player_status: "ACT", birth_date: "8/29/1994",height:"6'2",weight:"209",college: "West Virginia")
Player.create(name: "DeOssie Dontte",player_number: "51",player_position: "DT", player_status: "ACT", birth_date: "1/21/1995",height:"5'9",weight:"167",college: "Memphis")
Player.create(name: "Edwards Mario",player_number: "99",player_position: "CB", player_status: "ACT", birth_date: "11/10/1990",height:"6'5",weight:"250",college: "Stanford")
Player.create(name: "Ellison Rhett",player_number: "85",player_position: "LB", player_status: "ACT", birth_date: "1/20/1989",height:"6'6",weight:"243",college: "Arizona")
Player.create(name: "Engram Evan",player_number: "88",player_position: "RB", player_status: "ACT", birth_date: "2/23/1995",height:"6'2",weight:"230",college: "Nebraska")
Player.create(name: "Flowers Ereack",player_number: "74",player_position: "LB", player_status: "ACT", birth_date: "3/20/1994",height:"5'11",weight:"191",college: "West Virginia")
Player.create(name: "Gallman Wayne",player_number: "22",player_position: "RB", player_status: "ACT", birth_date: "1/3/1995",height:"6'5",weight:"256",college: "South Dakota State")
Player.create(name: "Gates Nick",player_number: "65",player_position: "OG", player_status: "ACT", birth_date: "4/3/1988",height:"6'2",weight:"265",college: "Michigan")
Player.create(name: "Goodson Bj",player_number: "93",player_position: "C", player_status: "ACT", birth_date: "7/25/1985",height:"6'0",weight:"196",college: "New Hampshire")
Player.create(name: "Greco Jhon",player_number: "73",player_position: "K", player_status: "ACT", birth_date: "5/16/1994",height:"6'2",weight:"230",college: "Eastern Illinois")
Player.create(name: "Halapio Jon",player_number: "75",player_position: "RB", player_status: "ACT", birth_date: "5/31/1994",height:"6'2",weight:"206",college: "Northern Iowa")
Player.create(name: "Hamiltom Antonio",player_number: "30",player_position: "DT", player_status: "ACT", birth_date: "10/7/1994",height:"6'2",weight:"296",college: "South Florida")
Player.create(name: "Harrison Damon",player_number: "98",player_position: "LB", player_status: "ACT", birth_date: "6/27/1992",height:"6'1",weight:"236",college: "Texas")
Player.create(name: "Hernandez Will",player_number: "71",player_position: "RB", player_status: "RES", birth_date: "9/16/1993",height:"6'4",weight:"221",college: "North Carolina")
Player.create(name: "Hill B J",player_number: "95",player_position: "DT", player_status: "ACT", birth_date: "2/14/1990",height:"6'3",weight:"218",college: "South Carolina")
Player.create(name: "Jenkins Janoris",player_number: "20",player_position: "CB", player_status: "ACT", birth_date: "12/20/1987",height:"6'0",weight:"204",college: "Ohio State")
Player.create(name: "Jordan Mike",player_number: "33",player_position: "DB", player_status: "ACT", birth_date: "5/8/1990",height:"6'6",weight:"317",college: "Oklahoma")
Player.create(name: "latimere cody",player_number: "12",player_position: "TE", player_status: "ACT", birth_date: "2/24/1992",height:"5'11",weight:"194",college: "Ohio State")
Player.create(name: "laulett Kyle",player_number: "17",player_position: "TB", player_status: "ACT", birth_date: "5/21/1996",height:"6'0",weight:"181",college: "Washington")
Player.create(name: "Manning Eli, ",player_number: "10",player_position: "OG", player_status: "ACT", birth_date: "11/5/1987",height:"6'3",weight:"295",college: "Cincinnati")
Player.create(name: "Martin Kareem",player_number: "96",player_position: "QB", player_status: "ACT", birth_date: "3/28/1985",height:"6'3",weight:"270",college: "Virginia")
Player.create(name: "Josh Maouro",player_number: "97",player_position: "K", player_status: "ACT", birth_date: "9/9/1992",height:"6'2",weight:"249",college: "Old Dominion")
Player.create(name: "Moor Kam",player_number: "29",player_position: "OG", player_status: "ACT", birth_date: "3/31/1996",height:"5'9",weight:"184",college: "Pittsburgh")
Player.create(name: "Patric Omeaha",player_number: "45",player_position: "LB", player_status: "ACT", birth_date: "3/31/1997",height:"6'8",weight:"346",college: "Unknown")
Player.create(name: "rielly curtis",player_number: "35",player_position: "DT", player_status: "PUP", birth_date: "1/6/1987",height:"5'10",weight:"200",college: "Wisconsin")
Player.create(name: "Shepard Russell",player_number: "81",player_position: "WR", player_status: "ACT", birth_date: "6/23/1990",height:"5'10",weight:"195",college: "Virginia")
Player.create(name: "Rosas Aldrick",player_number: "2",player_position: "TE", player_status: "ACT", birth_date: "4/6/1994",height:"6'0",weight:"191",college: "LSU")
Player.create(name: "Smith Shane",player_number: "87",player_position: "OG", player_status: "ACT", birth_date: "1/21/1984",height:"6'4",weight:"340",college: "Oregon")
Player.create(name: "Shane Sith ",player_number: "31",player_position: "RB", player_status: "ACT", birth_date: "8/5/1993",height:"6'3",weight:"223",college: "Washington")
Player.create(name: "Solder Nate",player_number: "43",player_position: "WR", player_status: "ACT", birth_date: "1/22/1982",height:"6'4",weight:"328",college: "Arkansas")
Player.create(name: "Stupar Nate",player_number: "3",player_position: "RB", player_status: "ACT", birth_date: "12/16/1994",height:"6'7",weight:"332",college: "Texas Christian")
Player.create(name: "Rosas Aldrick",player_number: "54",player_position: "C", player_status: "ACT", birth_date: "11/3/1990",height:"6'1",weight:"240",college: "Virginia")
Player.create(name: "Skolick Kristsjan",player_number: "23",player_position: "LB", player_status: "RES", birth_date: "1/22/1992",height:"6'4",weight:"257",college: "California")
Player.create(name: "Alex Tanney",player_number: "3",player_position: "LB", player_status: "ACT", birth_date: "10/29/1993",height:"6'4",weight:"303",college: "Oregon State")
Player.create(name: "Thomas Michel",player_number: "77",player_position: "RB", player_status: "RES", birth_date: "2/5/1993",height:"6'7",weight:"258",college: "Missouri State")
Player.create(name: "Vernon Oliver",player_number: "70",player_position: "RB", player_status: "ACT", birth_date: "1/20/1994",height:"5'10",weight:"208",college: "West Virginia")
Player.create(name: "Webb Bw",player_number: "82",player_position: "RB", player_status: "ACT", birth_date: "6/20/1983",height:"5'6",weight:"190",college: "Kansas State")
Player.create(name: "William Jordan",player_number: "54",player_position: "CB", player_status: "ACT", birth_date: "10/7/1993",height:"6'6",weight:"227",college: "Indiana")
Player.create(name: "Wheeler Card",player_number: "52",player_position: "QB", player_status: "ACT", birth_date: "3/29/1997",height:"6'5",weight:"251",college: "Florida State")
Player.create(name: "Kerry Wilams",player_number: "94",player_position: "DT", player_status: "ACT", birth_date: "1/15/1994",height:"6'4",weight:"299",college: "Washington State")
Player.create(name: "Tanny Alex",player_number: "23",player_position: "RB", player_status: "ACT", birth_date: "6/16/1993",height:"6'6",weight:"320",college: "Texas Christian")
Player.create(name: "Mike Wallace",player_number: "72",player_position: "LBS", player_status: "ACT", birth_date: "8/1/1986",height:"6'0",weight:"200",college: "Mississippi")


# Player.all.each_with_index{|player, index| player.id = index + 1}



# PlayerCard.destroy_all
# PlayerCard.create(team_id: Team.all.first.id, player_id:Player.all.first.id)
# Player.all[0].team = abc
# PlayerCard.create(team_id:, player_id:)
