Team.destroy_all
Team.create(name: "Philadelphia Eagles")
Team.create(name: "New York Giants")
abc = Team.create(name: "New York Jets")


Player.destroy_all
#jets
Player.create(name: "Jamal Adams",player_number: "33", player_status: "ACT", birth_date: "10/17/1995",height:"6'1",weight:"213",college: "LSU")
Player.create(name: "Robby Anderson",player_number: "11", player_status: "ACT", birth_date: "5/9/1993",height:"6'3",weight:"190",college: "Temple")
Player.create(name: "Henry Anderson",player_number: "96", player_status: "ACT", birth_date: "8/3/1991",height:"6'6",weight:"301",college: "Stanford")
Player.create(name: "Jeremiah Attaochu",player_number: "55", player_status: "ACT", birth_date: "1/17/1993",height:"6'3",weight:"252",college: "Georgia Tech")
Player.create(name: "Kelvin Beachum",player_number: "68", player_status: "ACT", birth_date: "6/8/1989",height:"6'3",weight:"308",college: "Southern Methodist")
Player.create(name: "Braden, Ben",player_number: "69", player_status: "ACT", birth_date: "3/9/1994",height:"6'6",weight:"329",college: "Michigan")
Player.create(name: "Terrence Brooks",player_number: "23", player_status: "ACT", birth_date: "3/2/1992",height:"5'11",weight:"200",college: "Florida State")
Player.create(name: "Juston Burris",player_number: "32", player_status: "ACT", birth_date: "8/4/1993",height:"6'0",weight:"212",college: "North Carolina State")
Player.create(name: "Trenton Cannon",player_number: "40", player_status: "ACT", birth_date: "7/23/1994",height:"5'11",weight:"185",college: "Virginia State")
Player.create(name: "James Carpenter",player_number: "77", player_status: "ACT", birth_date: "3/22/1989",height:"6'5",weight:"321",college: "Alabama")
Player.create(name: "Morris Claiborne",player_number: "21", player_status: "ACT", birth_date: "2/7/1990",height:"5'11",weight:"192",college: "LSU")
Player.create(name: "Brandon Copeland",player_number: "51", player_status: "ACT", birth_date: "7/2/1991",height:"6'3",weight:"263",college: "Pennsylvania")
Player.create(name: "Isaiah Crowell",player_number: "20", player_status: "ACT", birth_date: "1/8/1993",height:"5'11",weight:"225",college: "Alabama State")
Player.create(name: "Sam Darnold",player_number: "14", player_status: "ACT", birth_date: "6/5/1997",height:"6'3",weight:"225",college: "USC")
Player.create(name: "Dozier, Dakota",player_number: "70", player_status: "ACT", birth_date: "4/30/1991",height:"6'4",weight:"313",college: "Furman")
Player.create(name: "Lac Edwards",player_number: "4", player_status: "ACT", birth_date: "4/27/1992",height:"6'4",weight:"209",college: "Sam Houston State")
Player.create(name: "Quincy Enunwa",player_number: "81", player_status: "ACT", birth_date: "5/31/1992",height:"6'2",weight:"225",college: "Nebraska")
Player.create(name: "Foley Fatukasi",player_number: "94", player_status: "ACT", birth_date: "3/4/1995",height:"6'4",weight:"318",college: "Connecticut")
Player.create(name: "Jonotthan Harrison",player_number: "78", player_status: "ACT", birth_date: "8/25/1991",height:"6'4",weight:"300",college: "Florida")
Player.create(name: "Thomas Hennessy",player_number: "42", player_status: "ACT", birth_date: "6/11/1994",height:"6'2",weight:"246",college: "Duke")
Player.create(name: "Chris Herndon",player_number: "89", player_status: "ACT", birth_date: "2/23/1996",height:"6'4",weight:"253",college: "Miami (Fla.)")
Player.create(name: "Neville Hewitt",player_number: "46", player_status: "ACT", birth_date: "4/6/1993",height:"6'2",weight:"234",college: "Marshall")
Player.create(name: "Ben Ijalana",player_number: "71", player_status: "RES", birth_date: "8/6/1989",height:"6'4",weight:"322",college: "Villanova")
Player.create(name: "Jordan Jenkins",player_number: "48", player_status: "ACT", birth_date: "7/1/1994",height:"6'3",weight:"259",college: "Georgia")
Player.create(name: "Trumaine Johnson",player_number: "22", player_status: "ACT", birth_date: "1/1/1990",height:"6'2",weight:"213",college: "Montana")
Player.create(name: "Derrick Jones",player_number: "31", player_status: "ACT", birth_date: "12/4/1994",height:"6'2",weight:"188",college: "Mississippi")
Player.create(name: "Jermaine Kearse",player_number: "10", player_status: "ACT", birth_date: "2/6/1990",height:"6'1",weight:"209",college: "Washington")
Player.create(name: "Darron Lee",player_number: "58", player_status: "ACT", birth_date: "10/18/1994",height:"6'1",weight:"232",college: "Ohio State")
Player.create(name: "Jordan Leggett",player_number: "86", player_status: "ACT", birth_date: "1/31/1995",height:"6'5",weight:"258",college: "Clemson")
Player.create(name: "Spencer Long",player_number: "61", player_status: "ACT", birth_date: "11/8/1990",height:"6'5",weight:"318",college: "Nebraska")
Player.create(name: "Frankie Luvu",player_number: "50", player_status: "ACT", birth_date: "9/19/1996",height:"6'3",weight:"236",college: "Washington State")
Player.create(name: "Josh Martin",player_number: "95", player_status: "ACT", birth_date: "11/7/1991",height:"6'3",weight:"245",college: "Columbia")
Player.create(name: "Maye, Marcus",player_number: "26", player_status: "ACT", birth_date: "3/9/1993",height:"6'0",weight:"207",college: "Florida")
Player.create(name: "Josh McCown",player_number: "15", player_status: "ACT", birth_date: "7/4/1979",height:"6'4",weight:"218",college: "Sam Houston State")
Player.create(name: "Elijah McGuire",player_number: "25", player_status: "RES", birth_date: "6/1/1994",height:"'10",weight:"214",college: "Louisiana-Lafayette")
Player.create(name: "Steve McLendon",player_number: "99", player_status: "ACT", birth_date: "1/3/1986",height:"6'3",weight:"310",college: "Troy")
Player.create(name: "Doug Middleton",player_number: "36", player_status: "ACT", birth_date: "9/25/1993",height:"6'0",weight:"210",college: "Appalachian State")
Player.create(name: "Miles, Rontez",player_number: "45", player_status: "PUP", birth_date: "11/25/1988",height:"6'0",weight:"203",college: "California (PA)")
Player.create(name: "Jason Myers",player_number: "2", player_status: "ACT", birth_date: "5/12/1991",height:"5'10",weight:"190",college: "Marist")
Player.create(name: "Parry Nickerson",player_number: "43", player_status: "ACT", birth_date: "10/11/1994",height:"5'10",weight:"182",college: "Tulane")
Player.create(name: "Charone Peake",player_number: "17", player_status: "ACT", birth_date: "10/16/1992",height:"6'2",weight:"209",college: "Clemson")
Player.create(name: "Mike Pennel",player_number: "98", player_status: "ACT", birth_date: "5/9/1991",height:"6'4",weight:"332",college: "Colorado State-Pueblo")
Player.create(name: "Kevin Pierre-Louis",player_number: "56", player_status: "SUS", birth_date: "10/7/1991",height:"6'0",weight:"230",college: "Boston College")
Player.create(name: "Bilal Powell",player_number: "29", player_status: "ACT", birth_date: "10/27/1988",height:"5'10",weight:"204",college: "Louisville")
Player.create(name: "Pryor, Terrelle",player_number: "1", player_status: "ACT", birth_date: "6/20/1989",height:"6'4",weight:"228",college: "Ohio State")
Player.create(name: "Brent Qvale",player_number: "79", player_status: "ACT", birth_date: "3/11/1991",height:"6'7",weight:"315",college: "Nebraska")
Player.create(name: "Andre Roberts",player_number: "3", player_status: "ACT", birth_date: "1/9/1988",height:"5'11",weight:"195",college: "The Citadel")
Player.create(name: "Darryl Roberts",player_number: "27", player_status: "ACT", birth_date: "11/26/1990",height:"6'0",weight:"182",college: "Marshall")
Player.create(name: "Rashard Robinson",player_number: "30", player_status: "SUS", birth_date: "7/23/1995",height:"6'2",weight:"177",college: "LSU")
Player.create(name: "Brandon Shell",player_number: "72", player_status: "ACT", birth_date: "2/6/1992",height:"6'5",weight:"324",college: "South Carolina")
Player.create(name: "Nathan Shepherd",player_number: "97", player_status: "ACT", birth_date: "10/9/1993",height:"6'4",weight:"315",college: "Fort Hays State")
Player.create(name: "Buster Skrine",player_number: "41", player_status: "ACT", birth_date: "4/26/1989",height:"5'9",weight:"185",college: "Tennessee-Chattanooga")
Player.create(name: "Neal Sterling",player_number: "85", player_status: "ACT", birth_date: "1/14/1992",height:"6'4",weight:"257",college: "Monmouth (N.J.)")
Player.create(name: "ArDarius Stewart",player_number: "18", player_status: "SUS", birth_date: "12/8/1993",height:"6'0",weight:"205",college: "Alabama")
Player.create(name: "Eric Tomlinson",player_number: "83", player_status: "ACT", birth_date: "4/22/1992",height:"6'6",weight:"263",college: "Texas-El Paso")
Player.create(name: "J.J. Wilcox",player_number: "27", player_status: "ACT", birth_date: "2/14/1991",height:"6'0",weight:"212",college: "Georgia Southern")
Player.create(name: "Leonard Williams",player_number: "92", player_status: "ACT", birth_date: "6/20/1994",height:"6'5",weight:"302",college: "USC")
Player.create(name: "Avery Williamson",player_number: "54", player_status: "ACT", birth_date: "3/9/1992",height:"6'1",weight:"246",college: "Kentucky")
Player.create(name: "Brian Winters",player_number: "67", player_status: "ACT", birth_date: "7/10/1991",height:"6'4",weight:"320",college: "Kent State")


PlayerCard.create(team_id: Team.all.first.id, player_id:Player.all.first.id)
# PlayerCard.destroy_all
# PlayerCard.create(team_id:, player_id:)
